### ISSUE TITLE
weatherlib.py:weather_report() add rain sensor plot

### ISSUE THREAD

**Issue by adriaanph** [ska-sa/katsdpscripts#237]
in https://github.com/ska-sa/katsdpscripts/edit/master/katsdpscripts/RTS/weatherlib.py
please add a plot to the report, for the anc_weather_rain sensor. note that this sensor is currently only available on AR1, not on RTS.

**Comment by ludwigschwardt** [comment]
Funny, I still have [this task](https://skaafrica.atlassian.net/browse/SPR1-1890) in my backlog :-)
