### ISSUE TITLE
Robustness of interferometric pointing reduction with sluggish antennas

### ISSUE THREAD

**Issue by adriaanph** [ska-sa/katsdpscripts#462]
(from Tinus Steyn, 9 Nov 2023)
> Please note that I have seen in the past (and thus suspect) that another reason for low elevation coverage below 30degEl is the fact that sometimes, there are certain APs that struggle to lock on target when MeerKAT observes at low elevations. So when we do data analysis, the analyse script picks this up and then for the compound scans where one or more APs could not lock, it gives 0 valid solutions for all the APs, not just those APs that could not lock during that compound scan. So then we have to [manually] remove the data from the entire compound scan before we fit a pointing model.

Suggested modifications to [the scripts](https://github.com/ska-sa/katsdpscripts/blob/master/AR1/reduction/interferometric_pointing/analyse_interferometric_pointing.py):
1. in addition to the current default or specified "ant_list", create a fall-back list of "very reliable antennas"
2.  in cases where there's no valid fit using ant_list, repeat the reduction with the fall-back list

**Comment by spassmoor** [comment]
@tinussteyn  could you send me a data set where this happens so that I can test a fix for this bug.

**Comment by tinussteyn** [comment]
Sure @spassmoor , can use dataset with capture block ID **1699031481**, where **m028** had issue locking it seems on some scans.
![Scan 56](https://github.com/ska-sa/katsdpscripts/assets/37139113/65d7910c-cf78-471d-bf96-dadc37ead928)

**Comment by tinussteyn** [comment]
Hi @spassmoor , from the latest pointing datasets I've identified the following APs that frequently struggle to lock on low elevation targets: **M001, M006, M007, M017, M028 and M046**. I've created a Jira ticket explaining the issues for site to investigate: https://skaafrica.atlassian.net/browse/OPS-4468.

**Comment by adriaanph** [comment]
@spassmoor & @tinussteyn i have created a PR with a solution to this bug. please review https://github.com/ska-sa/katsdpscripts/issues/462.

**Comment by adriaanph** [comment]
@spassmoor & @tinussteyn note that i believe this has been resolved with https://github.com/ska-sa/katsdpscripts/pull/463, so i'll resolve this now.
